//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// CT_CIVIL.rc에서 사용되고 있습니다.
//
#define IDOK                            1
#define IDCANCEL                        2
#define IDC_HELP                        3
#define ID_ARI_HELP                     3
#define ID_CALS_HELP                    3
#define ID_AZT_HELP                     3
#define ID_CEX_HELP                     3
#define ID_COA_HELP                     3
#define ID_CIM_HELP                     3
#define IDCANCEL2                       3
#define ID_CSR_HELP                     3
#define ID_CST_HELP                     3
#define ID_CUT_HELP                     3
#define ID_DCG_HELP                     3
#define ID_DCON_HELP                    3
#define ID_DCW_HELP                     3
#define ID_DFB_HELP                     3
#define ID_DLG_HELP                     3
#define ID_DSLO_HELP                    3
#define ID_DSTA_HELP                    3
#define ID_FEL_HELP                     3
#define ID_GCS_HELP                     3
#define ID_GST_HELP                     3
#define ID_STT_HELP                     3
#define ID_TTP_HELP                     3
#define ID_WCZ_HELP                     3
#define ID_ZVL_HELP                     3
#define ID_ZVT_HELP                     3
#define IDS_PROJNAME                    100
#define IDS_STRING101                   101
#define IDS_SELECT_ENTITY               101
#define IDD_DIALOG1                     102
#define IDS_STRING102                   102
#define IDS_INSERT_TEXT                 102
#define IDD_NSLO                        103
#define IDS_STRING103                   103
#define IDS_CHECK_STRING                103
#define IDB_BITMAP1                     104
#define IDS_STRING104                   104
#define IDS_SELECT_TEXT                 104
#define IDB_BITMAP2                     105
#define IDS_STRING105                   105
#define IDS_CHECK_ENTITY                105
#define IDB_BITMAP3                     106
#define IDS_STRING106                   106
#define IDS_LAYER_SELECT                106
#define IDD_GEL                         107
#define IDS_STRING107                   107
#define IDS_FILENAME                    107
#define IDD_DSLO                        108
#define IDS_STRING108                   108
#define IDS_PROC_RESULT                 108
#define IDS_STRING109                   109
#define IDS_DOC_NAME                    109
#define IDB_BITMAP4                     110
#define IDS_STRING110                   110
#define IDS_SHEET                       110
#define IDB_BITMAP5                     111
#define IDS_STRING111                   111
#define IDS_CHECK_EXCEL                 111
#define IDD_CEX                         112
#define IDS_STRING112                   112
#define IDS_SETUP_EXCEL                 112
#define IDS_STRING113                   113
#define IDS_FIND_EXCEL                  113
#define IDB_BITMAP6                     114
#define IDS_STRING114                   114
#define IDS_NUMBER                      114
#define IDB_BITMAP7                     115
#define IDS_STRING115                   115
#define IDS_PATH                        115
#define IDB_BITMAP8                     116
#define IDS_STRING116                   116
#define IDB_BITMAP9                     117
#define IDS_STRING117                   117
#define IDS_BLOCKNAME                   117
#define IDC_COMBO1                      118
#define IDC_CBXLAYER                    118
#define IDD_CIM                         118
#define IDC_LAYER                       118
#define IDC_CSTYLE                      118
#define IDS_STRING118                   118
#define IDC_CBXSTALAYER                 118
#define IDC_CBX_LAYER                   118
#define IDC_ARI_CMBLAYER                118
#define IDC_DCG_COMBO_MAINLAYER         118
#define IDS_COMPLETE                    118
#define IDC_RADIO1                      119
#define IDD_DCW                         119
#define IDC_CLAYER                      119
#define IDS_STRING119                   119
#define IDC_STT_CBXDOT                  119
#define IDS_NOFORM                      119
#define IDC_RADIO2                      120
#define IDD_WCZ                         120
#define IDS_STRING120                   120
#define IDC_STT_CBXLINE                 120
#define IDS_COMPLETE_EXPORT             120
#define IDC_RADIO3                      121
#define IDC_LINE                        121
#define IDS_STRING121                   121
#define IDD_DSTA                        121
#define IDC_STT_CBXTEXT                 121
#define IDS_MODIFY_CHECK                121
#define IDC_BLOCK                       122
#define IDS_STRING122                   122
#define IDI_ICON1                       122
#define IDC_STT_CBXLAYERDOT             122
#define IDC_ARI_RADIO4                  122
#define IDC_DCG_COMBO_SUBLAYER          122
#define IDS_CHECK_BLOCK                 122
#define IDC_POLYLINE                    123
#define IDS_STRING123                   123
#define IDD_COA                         123
#define IDC_ARI_CMBSTYLE                123
#define IDC_DCG_COMBO_TEXTLAYER         123
#define IDS_SELECT_BLOCK                123
#define IDC_CIRCLE                      124
#define IDS_STRING124                   124
#define IDD_XYB                         124
#define IDC_CALS_RADCERTAIN2            124
#define IDS_CHECK_ENTITY_BLOCK          124
#define IDC_CHKDRAWLINE                 125
#define IDC_TEXT                        125
#define IDS_STRING125                   125
#define IDS_ACCESS_BLOCK                125
#define IDC_EDTMAXDIST                  126
#define IDC_DONUT                       126
#define IDC_POINTBTN                    126
#define IDS_STRING126                   126
#define IDB_BITMAP_ORDER1               126
#define IDS_EXTRACT_BLOCK               126
#define IDC_CHKCHANGELAYER              127
#define IDC_TEXTFILE                    127
#define IDC_CIRCLEBTN                   127
#define IDS_STRING127                   127
#define IDB_BITMAP10                    127
#define IDC_BCOLOR                      128
#define IDC_POINT                       128
#define IDC_BLOCKBTN                    128
#define IDS_STRING128                   128
#define IDD_ZVT                         128
#define IDB_BITMAP_ORDER3               128
#define IDS_IMPORT_CAD                  128
#define IDC_EDTAUTODIST                 129
#define IDC_ARC                         129
#define IDS_STRING129                   129
#define IDD_ZVL                         129
#define IDB_BITMAP_ORDER4               129
#define IDC_BCOLOR2                     129
#define IDC_CHKAUTODRAW                 130
#define IDC_ZAXIS                       130
#define IDS_STRING130                   130
#define IDD_TTP                         130
#define IDC_STTBIT1                     131
#define IDC_EXCEPT                      131
#define IDS_STRING131                   131
#define IDD_FEL                         131
#define IDC_STTBIT2                     132
#define IDC_CONTEXT                     132
#define IDS_STRING132                   132
#define IDD_DCON                        132
#define IDC_STTBIT3                     133
#define IDC_CHKARRAY                    133
#define IDS_STRING133                   133
#define IDB_FORM1                       133
#define IDC_STTWIDTH                    134
#define IDC_POINTEDIT                   134
#define IDS_STRING134                   134
#define IDB_FORM2                       134
#define IDC_BSELECT                     135
#define IDS_STRING135                   135
#define IDB_FORM3                       135
#define IDC_PATH                        136
#define IDS_STRING136                   136
#define IDB_FORM4                       136
#define IDC_STT_BSELECT2                136
#define IDC_CHKCHANGECLAYER             136
#define IDC_CHKADDPOINT                 137
#define IDC_PATHINPUT                   137
#define IDS_STRING137                   137
#define IDB_FORM5                       137
#define IDC_STT_BSELECT3                137
#define IDC_ALL_DEL                     137
#define IDC_CHKEXTEND                   138
#define IDC_Colon                       138
#define IDS_STRING138                   138
#define IDD_CST                         138
#define IDC_STT_BSELECT4                138
#define IDC_EDTEXTENDSTR                139
#define IDC_SPACE                       139
#define IDS_STRING139                   139
#define IDD_FE                          139
#define IDC_BTN_ACTIVEDWG_ADD           139
#define IDC_EDTSCALE                    140
#define IDC_SET                         140
#define IDS_STRING140                   140
#define IDD_GST                         140
#define IDC_CALS_BTN_ADDFOLDER          140
#define IDC_EDTELSTR                    141
#define IDC_RIGHT                       141
#define IDS_STRING141                   141
#define IDD_STT                         141
#define IDC_BTN_BOTTOM                  141
#define IDC_EDTDOTNUM                   142
#define IDC_EXCEL                       142
#define IDS_STRING142                   142
#define IDC_FEDECIMAL                   142
#define IDD_FW                          142
#define IDC_CALS_BTN_ADDDWG             142
#define IDC_COMBO_WRITE_TARGET          142
#define IDC_SPINDOT                     143
#define IDC_LEFT                        143
#define IDC_2DPOLY                      143
#define IDS_STRING143                   143
#define IDC_FESCALE                     143
#define IDD_AZT                         143
#define IDC_EDTTEXTHEIGHT               144
#define IDC_DOWN                        144
#define IDS_STRING144                   144
#define IDD_GCS                         144
#define IDC_UP                          145
#define IDS_STRING145                   145
#define IDC_FEPREFACE                   145
#define IDC_BTN_DOWN                    145
#define IDD_SLT                         145
#define IDC_CHKPTZVALUE                 145
#define IDC_BLAYERSELECT                146
#define IDC_EXCELFILE                   146
#define IDS_STRING146                   146
#define IDC_FEHEIGHT                    146
#define IDB_SLT1                        146
#define IDC_BTN_FILELISTSAVE            146
#define IDC_BTEXTSELECT                 147
#define IDC_PIC1                        147
#define IDS_STRING147                   147
#define IDB_SLT2                        147
#define IDC_CHKDRAWARROW                148
#define IDC_PIC2                        148
#define IDR_MENU1                       148
#define IDC_BTN_OPENDWG_ADD             148
#define IDC_BUTTON1                     149
#define IDC_PIC3                        149
#define IDD_DLG                         149
#define IDC_EDIT1                       150
#define IDC_PIC4                        150
#define IDC_EDIT_3                      150
#define IDC_EDTSTADIST                  150
#define IDC_EDTXOFFSET                  150
#define IDC_EDTLENGTH                   150
#define IDC_EDT_BASE                    150
#define IDC_STT_EDTSCALE                150
#define IDC_EDT_VSCALE                  150
#define IDD_CSR                         150
#define IDC_EDT_SCALE                   150
#define IDC_CSR_SCALE                   150
#define IDC_CALS_BUTTON2                150
#define IDC_BUTTON3                     150
#define IDC_CHK_EL_CONTINUE             150
#define IDC_EDIT2                       151
#define IDC_SETSPACE                    151
#define IDC_EDIT_2                      151
#define IDC_EDTSTALINE                  151
#define IDC_EDTY                        151
#define IDC_EDTTEXTWIDHT                151
#define IDC_EDTYOFFSET                  151
#define IDC_EDTHEIGHT                   151
#define IDC_EDT_LAYERNAME               151
#define IDC_STT_EDTSTLENGTH             151
#define IDC_EDT_GRIDDIST                151
#define IDC_EDT_TRIMDIST                151
#define IDC_CSR_TRIMDIST                151
#define IDC_ARI_DOTIA                   151
#define IDC_DCG_EDT_DOWN                151
#define IDC_CALS_EDTCERTAIN             151
#define IDC_BUTTON4                     151
#define IDC_MINUS                       152
#define IDC_STT_EDTDIST                 152
#define IDD_CUT                         152
#define IDC_CSR_BUTTON1                 152
#define IDC_ARI_DOTR                    152
#define IDC_SLT_ARROWHEIGHT             152
#define IDC_DCG_EDT_LEFT                152
#define IDC_CALS_BUTTON3                152
#define IDC_SPIN1                       153
#define IDC_PLUS                        153
#define IDC_SPIN_2                      153
#define IDC_SPNDECIMALPOINT             153
#define IDC_EDTDIST                     153
#define IDC_SPN_BRIGHT                  153
#define IDC_STT_EDTHEIGHT               153
#define IDC_ARI_SPINXY                  153
#define IDC_DCG_EDT_RIGHT               153
#define IDC_CALS_BUTTON4                153
#define IDC_POINT_SPIN                  153
#define IDC_STT_EDTWIDTH                154
#define IDC_ARI_SPINIA                  154
#define IDC_DCG_EDT_SCALE               154
#define IDC_SPIN2                       155
#define IDC_SPIN_1                      155
#define IDC_BTN_TOP                     155
#define IDC_ARI_SPINR                   155
#define IDC_SLT_LEADER                  155
#define IDC_DCG_EDT_MAINWIDTH           155
#define IDC_CHECK1                      156
#define IDC_POINTCOLORBTN               156
#define IDC_BTN_UP                      156
#define IDC_ARI_SPINTL                  156
#define IDC_SLT_EDTDOT                  156
#define IDC_EDTSTARTVALUE               157
#define IDC_XYCHANGE                    157
#define IDC_CHECKFEHPOINT               157
#define IDC_ARI_DOTTL                   157
#define IDC_SLT_EDTHORSCALE             157
#define IDC_DCG_EDT_MAINLINESCALE       157
#define IDC_CHECK_CLAYER                157
#define IDC_EDTENDVALUE                 158
#define IDC_PATHBTN                     158
#define IDC_ARI_SPINCL                  158
#define IDC_SLT_EDTVERSCALE             158
#define IDC_DCG_EDT_SUBWIDTH            158
#define IDC_BSELECTELVALUE              159
#define IDC_TEXTBTN                     159
#define IDC_ARI_DOTCL                   159
#define IDC_SLT_EDTDISTDOT              159
#define IDC_DCG_EDT_SUBLINESCALE        159
#define IDC_CONLINECOLORBTN             160
#define IDC_EDIT_1                      160
#define IDC_ARI_SPINSL                  160
#define IDC_SLT_EDTHEIGHTDOT            160
#define IDC_DCG_BTN_SUBCOLOR            160
#define IDC_ZVALCOLORBTN                161
#define IDC_STATIC_1                    161
#define IDB_CSR1                        161
#define IDC_ARI_DOTSL                   161
#define IDC_DCG_BTN_TEXTCOLOR2          161
#define IDC_TEXTLOAD                    162
#define IDC_STATIC_2                    162
#define IDB_CSR2                        162
#define IDC_ARI_BSELECT2                162
#define IDC_RADIO_FORM_OPTION2          162
#define IDC_TEXTLAYER                   163
#define IDC_STATIC_3                    163
#define IDD_ARI                         163
#define IDC_ARI_BSELECT3                163
#define IDB_BITMAP_ORDER2               163
#define IDC_TEXTSIZE                    164
#define IDC_SPIN3                       164
#define IDC_STATIC_4                    164
#define IDC_SLT_SPIN1                   164
#define IDC_XOFF                        165
#define IDC_EDTSTASTART                 165
#define IDC_SLT_SPIN2                   165
#define IDD_DCG                         165
#define IDC_YOFF                        166
#define IDC_CHKSTACIRCLE                166
#define IDC_SLT_SPIN3                   166
#define IDD_CFM                         166
#define IDC_RADIO_WRITE_TYPE1           166
#define IDC_SELTEXT                     167
#define IDC_EDTSTACIRCLE                167
#define IDD_CALS                        167
#define IDC_BTNSTASELECT                168
#define IDC_FIRST_TXT                   168
#define IDC_CBXTEXTPOSITION             169
#define IDC_CHKTEXTVISIBLE              170
#define IDC_RADIO_WRITE_TYPE2           170
#define IDC_EDTTEXTDIST                 171
#define IDC_EDTTEXTOFFSET               172
#define IDC_EDTDECIMALPOINT             173
#define IDC_BNAME                       174
#define IDC_RADIO_WRITE_TYPE3           174
#define IDC_EDTTEXTOFFSET2              174
#define IDC_ZCHECK                      175
#define IDC_EDTTEXTSIZE                 175
#define IDC_3DPOLY                      176
#define IDC_BTNTEXTSELECT               176
#define IDC_EDTTEXTOFFSET3              176
#define IDC_SELLAYER                    177
#define IDC_TEXTSEL                     177
#define IDC_CBXTEXTSTYLE                177
#define IDC_CBXTEXTLAYER                178
#define IDC_CBXTEXTSTYLE2               178
#define IDC_POINTPICCOLOR               179
#define IDC_BTNTEXTCOLOR                179
#define IDC_COMBO_TEXT_OPTION_FONT      179
#define IDC_CBXTEXTSTYLE3               179
#define IDC_CONLINE                     180
#define IDC_CHKONEWAY                   180
#define IDC_RADSTA                      180
#define IDC_EDTTEXTOFFSET4              180
#define IDC_CONLINELAYER                181
#define IDC_FACTOR                      181
#define IDC_RADNO                       181
#define IDB_CLEAR                       181
#define IDC_EDTTEXTOFFSET5              181
#define IDC_TCPICCOLOR                  182
#define IDC_THICKNESS                   182
#define IDC_CHKSTASTART                 182
#define IDC_EDTTEXTOFFSET6              182
#define IDC_CONLINEPICCOLOR             183
#define IDC_COLORFACTOR                 183
#define IDC_BTNSTACOLOR                 183
#define IDC_ZVALPICCOLOR                184
#define IDC_FACTORSPACE                 184
#define IDC_STTSTACOLORINDEX            184
#define IDD_XY                          184
#define IDC_SELCONLINE                  185
#define IDC_DIVISION                    185
#define IDC_STTTEXTCOLORINDEX           185
#define IDC_COMBO_TEXT_OPTION_LAYER     185
#define IDC_CUTPOINT                    186
#define IDC_CHKARROW                    186
#define IDC_BUTTON2                     186
#define IDC_BTEXT                       186
#define IDC_SLT_BTN4                    186
#define IDC_DCG_MAINEXTRACT             186
#define IDC_CALS_BUTTON1                186
#define IDC_STATICDCS                   187
#define IDC_CUTPOINTLAYER               187
#define IDC_RANGLE                      187
#define IDC_CHECK2                      187
#define IDC_CHKEXPLODE                  187
#define IDC_CHKZV                       187
#define IDC_CHECKFEHORIZONTAL           187
#define IDC_STT_CHECK2                  187
#define IDC_CHK_CONTINUOUS              187
#define IDC_CHK_ROUNDINGTRIM            187
#define IDC_CSR_DIVIDE                  187
#define IDC_ARI_CHECK1                  187
#define IDC_SLT_BTN5                    187
#define IDC_DCG_CHK_MAINCON             187
#define IDC_POINTSIZE                   188
#define IDC_RECTANGLE                   188
#define IDC_BPOINT                      188
#define IDC_STT_CHECK3                  188
#define IDC_ARI_CHECK2                  188
#define IDC_CHECK3                      188
#define IDC_DIAMETER                    189
#define IDC_TEXTHEIGHT                  189
#define IDC_EDTX                        189
#define IDC_STT_CHECK4                  189
#define IDC_ARI_CHECK3                  189
#define IDC_DCG_SUBEXTRACT              189
#define IDC_CHECK4                      189
#define IDC_SCALE                       190
#define IDC_TEXTWIDTH                   190
#define IDC_ARI_CHECK4                  190
#define IDC_DCG_TEXTEXTRACT             190
#define IDC_CHECK5                      190
#define IDC_SELZVALUE                   191
#define IDC_CELVATION                   191
#define IDC_ARI_CHECK5                  191
#define IDC_DCG_TEXTLAYEREXTRACT        191
#define IDC_COMBO_TEXT_OPTION_ANGLE     191
#define IDC_CHECK6                      191
#define IDC_ZVALUE                      192
#define IDC_COABIT                      192
#define IDC_ARI_CHECK6                  192
#define IDC_CHECK7                      192
#define IDC_ZVALUELAYER                 193
#define IDC_SELPOINT                    194
#define IDC_CBXPOINTLAYER               194
#define IDC_TEXTSIZE4                   195
#define IDC_RADRIGHT                    195
#define IDC_FILELISTSAVE                195
#define IDC_XOFF4                       196
#define IDC_CHKCP                       196
#define IDC_COMBO_WRITE_DWG_NAME_FONT   196
#define IDC_YOFF4                       197
#define IDC_RADUP                       197
#define IDC_PCNT                        198
#define IDC_RADDOWN                     198
#define IDC_RADLEFT                     199
#define IDC_RADLINE                     201
#define IDC_COMBO_WRITE_DWG_NAME_LAYER  201
#define IDC_RADPLINE                    202
#define IDC_LIST_FILES                  203
#define IDC_RAD3DPLINE                  203
#define IDC_RADINSERTPOINT              204
#define IDC_RADALIGNPOINT               205
#define IDC_COMBO_EXTENSION             205
#define IDC_EDTHEADER                   206
#define IDC_COMBO_WRITE_DWG_NAME_TEXT_ANGLE 206
#define IDC_EDIT4                       207
#define IDC_EDTPOINT                    207
#define IDC_STT_EDTDOT                  207
#define IDC_ARI_EDTHEIGHT               207
#define IDC_CALS_EDTSEARCH              207
#define IDC_STT_EDTDIST2                208
#define IDC_RADARROW                    209
#define IDC_STT_EDTOFFSET               209
#define IDC_STATICRADTEXT               210
#define IDC_EDT_BRIGHT                  211
#define IDC_COMBO_WRITE_DWG_NAME_ALIGN  211
#define IDC_CHK_LAYERCOLOR              213
#define IDC_BTN_COLOR                   214
#define IDC_STATICFWLAYER               214
#define IDC_STTCOLOR                    214
#define IDC_STATICFWTXTLAYER            215
#define IDC_RAD_CIVIL                   215
#define IDC_FWLINELAYER                 216
#define IDC_RAD_CAD                     216
#define IDC_FWTXTLAYER                  217
#define IDC_EDT_LINESCALE               217
#define IDC_STTCOLOR2                   217
#define IDC_STATICFWTXTHEIGHT           218
#define IDC_CHK_STANDARD                218
#define IDC_STATICFWTXTWIDTH            219
#define IDC_STT_COLOR                   219
#define IDC_STATICFWLDLENGTH            220
#define IDC_CHK_EXPLODE                 220
#define IDC_CSR_EXPLODE                 220
#define IDC_STATICFWLDLENGTH2           221
#define IDC_RAD_SELECTDIST              221
#define IDC_CSR_RAD1                    221
#define IDC_FWFORM1                     222
#define IDC_RAD_HORIZON                 222
#define IDC_CSR_RAD3                    222
#define IDC_FWTXTHEIGHT                 223
#define IDC_RAD_INTERSECTION            223
#define IDC_CSR_RAD2                    223
#define IDC_FWTXTWIDTH                  224
#define IDC_CHK_BASETRIM                224
#define IDC_CSR_TRIM                    224
#define IDC_FWLDLENGTH                  225
#define IDC_CHKTEXT                     225
#define IDC_FWDECIMAL                   226
#define IDC_CUT_STATIC1                 226
#define IDC_STATICFWPREFACE             227
#define IDC_CSR_BUTTON2                 227
#define IDC_FWPREFACE                   228
#define IDC_CSR_STATIC                  228
#define IDC_STATICFWNOTATION            229
#define IDC_ARI_NONAME                  229
#define IDC_FWFORM2                     230
#define IDC_ARI_DOTXY                   230
#define IDC_FWFORM3                     231
#define IDC_ARI_RADIO1                  231
#define IDC_FWFORM4                     232
#define IDC_ARI_RADIO2                  232
#define IDC_FWFORM5                     233
#define IDC_ARI_RADIO3                  233
#define IDC_ARI_BSELECT1                234
#define IDC_CALS_RADZSORT               234
#define IDC_FORMGROUP                   235
#define IDC_PICFORM                     237
#define IDC_SEL_DEL                     237
#define IDC_CHECKFELEADER               238
#define IDC_SORT1                       238
#define IDC_DCG_CHK_DELGRID             238
#define IDC_STATICFEDOT                 239
#define IDC_SORT2                       239
#define IDC_DCG_CHK_ELLEFT              239
#define IDC_STATICFELAYER               240
#define IDC_DCG_CHK_ELRIGHT             240
#define IDC_CALS_SEL_OPEN               240
#define IDC_STATICFEPREFACE             241
#define IDC_DCG_EDT_TEXTHEIGHT          241
#define IDC_STATICFEHEIGHT              242
#define IDC_DCG_EDT_TEXTWIDTH           242
#define IDC_FELAYER                     243
#define IDC_DCG_COMBO_TEXTSTYLE         243
#define IDC_STATICFESCALE               244
#define IDC_DCG_RAD1                    244
#define IDC_CHECKFESPOINT               245
#define IDC_DCG_RAD2                    245
#define IDC_STATICFEEL                  246
#define IDC_DCG_RAD3                    246
#define IDC_RADIOFEUP                   247
#define IDC_DCG_EDT_UP                  247
#define IDC_RADIOFEDOWN                 248
#define IDC_DCG_CHK_STANDARD            248
#define IDC_DCG_BTN_MAINCOLOR           249
#define IDC_STT_STATIC1                 250
#define IDC_DCG_MAINPRINCOLOR           250
#define IDC_STT_STATIC_SCALE            251
#define IDC_DCG_SUBCOLORSTATIC          251
#define IDC_STT_STATIC_LENGTH           252
#define IDC_DCG_MAINCOLORSTATIC         252
#define IDC_STT_STATIC_PTWIDTH          253
#define IDC_DCG_TEXTCOLORSTATIC         253
#define IDC_EXCEL_BOX                   253
#define IDC_STT_STATIC_TXTHEIGHT        254
#define IDC_CALS_RADEXCEL               254
#define IDC_SORT3                       254
#define IDC_STATIC_TXTWIDTH             255
#define IDC_CALS_RADCAD                 255
#define IDC_SORT4                       255
#define IDC_STT_STATIC_TXTTYPE          256
#define IDC_EMTT_RADEXCEL               256
#define IDC_STT_STATIC_DOT              257
#define IDC_EMTT_RADCAD                 257
#define IDC_STT_STATIC2                 258
#define IDC_SLT_STATIC_COLOR            258
#define IDC_CALS_BTNEXTRACT             258
#define IDC_STT_STATIC_OFFSET           259
#define IDC_EMTT_LISTFILES              259
#define IDC_STT_STATIC_LAYERLINE        260
#define IDC_EMTT_RADMODEL               260
#define IDC_STT_STATIC_LAYERTXT         261
#define IDC_EMTT_RADLAYOUT              261
#define IDC_STT_STATIC_LAYERDOT         262
#define IDC_EMTT_RADMODELLAY            262
#define IDC_STT_RADSTATION              263
#define IDC_CALS_EDTERROR               263
#define IDC_EMTT_LISTFILES3             263
#define IDC_EMTT_TXT_LIST               263
#define IDC_STT_RADNUMBER               264
#define IDC_CALS_LISTFILES              264
#define IDC_EMTT_RADCERTAIN             264
#define IDC_STT_CHECK1                  265
#define IDC_CALS_BTN_ACTIVEDWG          265
#define IDC_STT_CBXTEXTTYPE             266
#define IDC_CALS_BTN_OPENDWG            266
#define IDC_STT_STATIC_M1               267
#define IDC_SLT_STATIC12                267
#define IDC_CALS_SEL_DEL                267
#define IDC_STT_STATIC_M2               268
#define IDC_SLT_STATIC13                268
#define IDC_CALS_ALL_DEL                268
#define IDC_STT_STATIC_M3               269
#define IDC_SLT_STATIC14                269
#define IDC_CALS_BTN_UP                 269
#define IDC_STT_BSELECT1                270
#define IDC_CALS_BTN_DOWN               270
#define IDC_GST_STATIC_MARK             271
#define IDC_SLT_CHECK2                  271
#define IDC_CALS_BTN_BOTTOM             271
#define IDC_GST_RADSTATION              272
#define IDC_SLT_CHECK3                  272
#define IDC_CALS_BTN_TOP                272
#define IDC_GST_RADNUMBER               273
#define IDC_SLT_STATIC4                 273
#define IDC_CALS_SORT1                  273
#define IDC_CST_RADEDIT                 274
#define IDC_GST_STATIC_STLENGTH         274
#define IDC_SLT_STATIC2                 274
#define IDC_CALS_SORT2                  274
#define IDC_GST_STATIC_DOT              275
#define IDC_SLT_STATIC5                 275
#define IDC_CALS_BTN_EXPORT             275
#define IDC_STATIC_COL                  275
#define IDC_STATICCOME                  276
#define IDC_CST_RADWRITE                276
#define IDC_GST_STATIC_SCALE            276
#define IDC_SLT_STATIC3                 276
#define IDC_CALS_LISTFILES2             276
#define IDC_POINTCOLOR                  277
#define IDC_GST_STATIC_DIST             277
#define IDC_SLT_STATIC6                 277
#define IDC_STATIC_COLOR_ATTR           277
#define IDC_EMTT_EDTCERTAIN             277
#define IDC_TCOLOR                      278
#define IDC_GST_CHECK2                  278
#define IDC_SLT_STATIC9                 278
#define IDC_CALS_BTN_EXPORT3            278
#define IDC_EMTT_RADACTIVE              278
#define IDC_CONCOLOR                    279
#define IDC_GST_CHECK1                  279
#define IDC_SLT_BSELECT2                279
#define IDC_STATIC_COLOR_ATTR2          279
#define IDC_EMTT_EDTSEARCH              279
#define IDC_ZVALCOLOR                   280
#define IDC_GST_STATIC_TXTHEIGHT        280
#define IDC_SLT_BSELECT3                280
#define IDC_CALS_BTN_IMPORT             280
#define IDC_GST_STATIC_PREFACE          281
#define IDC_AZT_BSELECT3                281
#define IDC_SLT_CHECK4                  281
#define IDC_STATIC_COL2                 281
#define IDC_EMTT_BTNEXTRACT             281
#define IDC_CST_STATIC_FOOTER           282
#define IDC_GST_EDTSTLENGTH             282
#define IDC_SLT_STATIC_RATIO            282
#define IDC_EMTT_RADZSORT               282
#define IDC_GST_CBXDOT                  283
#define IDC_AZT_CHECK1                  283
#define IDC_EMTT_RADNSORT               283
#define IDC_GST_EDTSCALE                284
#define IDC_AZT_CHECK2                  284
#define IDC_EMTT_RADNMSORT              284
#define IDC_GST_EDTDIST                 285
#define IDC_AZT_CHECK3                  285
#define IDC_EMTT_RADZMSORT              285
#define IDC_GST_EDTHEIGHT               286
#define IDC_CALS_RADNSORT               286
#define IDC_EMTT_EDTERROR               286
#define IDC_GST_BSELECT                 287
#define IDC_CALS_RADNMSORT              287
#define IDC_EMTT_BTN_ADDDWG             287
#define IDC_GST_EDTPREFACE              288
#define IDC_CALS_RADZMSORT              288
#define IDC_EMTT_BTN_ADDFOLDER          288
#define IDC_GST_GROUP                   289
#define IDC_EMTT_BTN_ACTIVEDWG          289
#define IDC_CST_GROUP                   290
#define IDC_GST_CHECK3                  290
#define IDC_EMTT_BTN_OPENDWG            290
#define IDC_CST_EDTFOOTER               291
#define IDC_EMTT_SEL_OPEN               291
#define IDC_CST_STATIC_MARK             292
#define IDC_EMTT_SEL_DEL                292
#define IDC_CST_RADSTATION              293
#define IDC_EMTT_ALL_DEL                293
#define IDC_CST_RADNUMBER               294
#define IDC_EMTT_BTN_UP                 294
#define IDC_CST_STATIC_DOT              295
#define IDC_EMTT_BTN_DOWN               295
#define IDC_CST_CBXDOT                  296
#define IDC_EMTT_BTN_TOP                296
#define IDC_CST_STATIC_DIST             297
#define IDC_EMTT_BTN_BOTTOM             297
#define IDC_CST_EDTDIST                 298
#define IDC_EMTT_BTN_EXPORT             298
#define IDC_CST_STATIC_TXTHEIGHT        299
#define IDC_EMTT_SORT1                  299
#define IDC_CST_EDTHEIGHT               300
#define IDC_EMTT_SORT2                  300
#define IDC_CST_BSELECT                 301
#define IDC_EMTT_LISTFILES2             301
#define IDC_CST_STATIC_PREFACE          302
#define IDC_EMTT_BTN_IMPORT             302
#define IDC_CST_EDTPREFACE              303
#define IDC_EMTT_BUTTON1                303
#define IDC_CST_STATIC                  304
#define IDC_EDIT_FORMOPTION_FORM_NAME   304
#define IDC_EMTT_BUTTON2                304
#define IDC_EMTT_BUTTON3                305
#define IDC_EMTT_BUTTON4                306
#define IDC_SELECT_TXT                  307
#define IDC_EMTT_TXT_ADD                308
#define IDC_GCS_STATIC_MARK             309
#define IDC_SLT_GROUP4                  309
#define IDC_EMTT_TXT_SUB                309
#define ID_GEL_HELP                     310
#define IDC_GCS_RADSTATION              310
#define IDC_SLT_GROUP5                  310
#define IDC_EMTT_TXT_CLEAR              310
#define IDC_GCS_RADNUMBER               311
#define IDC_LIST1                       311
#define IDC_GCS_STATIC_DOT              313
#define IDC_GCS_CBXDOT                  314
#define IDC_GCS_STATIC_DIST             315
#define IDC_GCS_EDTDIST                 316
#define IDC_GCS_CHECK1                  317
#define IDD_ADN                         317
#define IDC_GCS_STATIC_REFROAD          318
#define IDC_EDIT_FORMOPTION_INSERT_POINT 318
#define IDD_CALS2                       318
#define IDC_GCS_STATIC_CORROAD          319
#define IDC_GCS_EDTREFROAD              320
#define IDC_GCS_EDTCORROAD              321
#define IDC_GCS_CHECK2                  322
#define IDC_SLT_BTN1                    323
#define IDC_BUTTON_FORMOPTION_INSERT_POINT 323
#define IDC_SLT_BTN2                    324
#define IDC_SLT_GROUP2                  326
#define IDC_SLT_RADPERCENT              327
#define IDC_AZT_FORM2                   328
#define IDC_SLT_RADRATIO                328
#define IDC_AZT_FORM3                   329
#define IDC_SLT_CHECK1                  329
#define IDC_SLT_BTN3                    330
#define IDC_SLT_STATIC1                 331
#define IDC_SLT_ARROWWIDTH              332
#define IDC_EDIT_INCREASE_START_NUMBER  332
#define IDC_SLT_STATIC7                 333
#define IDC_SLT_STATIC8                 334
#define IDC_EDIT_INCREASE_DIGIT         334
#define IDC_SLT_STATIC10                335
#define IDC_AZT_STATIC2                 336
#define IDC_SLT_BSELECT1                336
#define IDC_SLT_STATIC11                337
#define IDC_SLT_STATIC15                338
#define IDC_AZT_STATIC6                 339
#define IDC_SLT_CBXTEXTTYPE             339
#define IDC_SPIN_DIGIT                  339
#define IDC_SLT_CBXLAYER                340
#define IDC_AZT_CBXTEXTSTYLE            341
#define IDC_SLT_EDTHEIGHT               341
#define IDC_SLT_STATIC_PERCENT          342
#define IDC_AZT_CBXLAYER2               343
#define IDC_SLT_PRINCOLOR               343
#define IDC_DCG_SUBPRINCOLOR            344
#define IDC_DCG_TEXTPRINCOLOR2          345
#define IDC_DCG_TEXTPRINCOLOR           345
#define IDC_CHECK_WRITE_DWG_NAME        349
#define IDC_CHECK_TEXT_OPTION_OLD_REMOVE 353
#define IDC_SLT_WRITE                   357
#define IDC_EDIT_TEXT_OPTION_TEXT_HEIGHT 357
#define IDC_AZT_GROUP1                  358
#define IDC_AZT_GROUP2                  359
#define IDC_AZT_GROUP4                  360
#define IDC_AZT_FORM1                   361
#define IDC_EDIT_TEXT_OPTION_TEXT_WIDTH 361
#define IDC_AZT_STATIC1                 362
#define IDC_AZT_STATIC3                 363
#define IDC_AZT_STATIC4                 364
#define IDC_EDIT_WRITE_DWG_NAME_POINT   364
#define IDC_AZT_STATIC5                 365
#define IDC_AZT_CBXLAYER1               366
#define IDC_AZT_BSELECT1                367
#define IDC_CHECK_WRITE_DWG_NAME_FULLPATH 367
#define IDC_AZT_BSELECT2                368
#define IDC_AZT_EDTHEIGHT               369
#define IDC_AZT_EDTWIDTH                370
#define IDC_CHECK_WRITE_DWG_NAME_FIELD  370
#define IDC_AZT_DOT                     371
#define IDC_AZT_SPIN                    372
#define IDC_AZT_OK                      373
#define IDC_IDC_CUT_WRITE               374
#define IDC_CUT_HEIGHT                  375
#define IDC_CHECK_WRITE_DWG_NAME_INC_EXT 375
#define IDC_CUT_SLOPE                   376
#define IDC_CUT_SCALE                   377
#define IDC_CUT_CBXLAYER                378
#define IDC_CUT_COLORBTN                379
#define IDC_EDIT_WRITE_DWG_NAME_TEXT_HEIGHT 379
#define IDC_CUT_BSELECT2                380
#define IDC_GROUP3                      381
#define IDC_CUT_STATIC_COLOR            382
#define IDC_CUT_PRINCOLOR               383
#define IDC_EDIT_WRITE_DWG_NAME_TEXT_WIDTH 383
#define IDC_CUT_MINHEIGHT               384
#define IDC_CUT_EXCEPT                  385
#define IDC_CUT_BSELECT1                386
#define IDC_EDIT_TOLERANCE              386
#define IDC_CUT_LSCALE                  387
#define IDC_CUT_CHECK2                  388
#define IDC_GROUP2                      389
#define IDC_GROUP1                      390
#define IDC_STATIC1                     391
#define IDC_STATIC4                     392
#define IDC_STATIC2                     393
#define IDC_STATIC5                     394
#define IDC_STATIC3                     395
#define IDC_STATIC6                     396
#define IDC_STATIC16                    397
#define IDC_STATIC17                    398
#define IDC_CUT_CHECK1                  399
#define IDC_CUT_WRITE                   400
#define IDC_COMBO_CROSSLAYER            401
#define IDC_EDIT_CROSSVLINELEN          402
#define IDC_EDIT_CROSSDSTDECPT          403
#define IDC_SPN_CROSSDSTDECPT           404
#define IDC_EDIT_CROSSHGTDECPT          405
#define IDC_SPN_CROSSHGTDECPT           406
#define IDC_EDIT_GROUNDLEVEL            407
#define IDC_CHECKSTATIONINPUT           408
#define IDC_CHECKDSTHGTDISP             409
#define IDC_RADIORELATIVE               410
#define IDC_RADIOABSOLUTE               411
#define IDC_CHECKEXCEPTZEROZ            412
#define IDC_CHECKONLYCROSSPT            413
#define IDC_BUTTON_CORSSLINESEL         414
#define IDC_BTNSELENT                   415
#define IDD_DFB                         416
#define IDC_SPIN_3                      417
#define IDC_BUTTON_TEXT_OPTION_FONT     427
#define IDC_BUTTON_WRITE_DWG_NAME_FONT  429
#define IDC_BUTTON_TEXT_OPTION_LAYER    440
#define IDC_BUTTON_WRITE_DWG_NAME_LAYER 443
#define IDC_BUTTON5                     447
#define IDC_BUTTON_WRITE_DWG_NAME_POINT 452
#define IDC_BUTTON7                     455
#define IDC_EDIT_DWG_NUMBER_PREFIX      514
#define IDC_EDIT_DWG_START_NUMBER       517
#define IDC_EDIT_INSERT_TEXT            519
#define IDC_STATIC_PREVIEW              522
#define IDC_LIST_DWG                    524
#define IDC_BUTTON_ADD_DWG              526
#define IDC_BUTTON_ADD_FOLDER           528
#define IDC_BUTTON_ADD_ACTIVE_DWG       529
#define IDC_BUTTON_ADD_OPEN_DWG         531
#define IDC_BUTTON_OPEN                 532
#define IDC_BUTTON_SEL_REMOVE           535
#define IDC_BUTTON_ALL_REMOVE           538
#define IDC_BUTTON_GO1                  541
#define IDC_BUTTONT_TOP                 543
#define IDC_BUTTON_UP                   545
#define IDC_BUTTON_DOWN                 547
#define IDC_BUTTON_BOTTOM               549
#define IDC_BUTTON_LIST_SAVE            551
#define IDC_BUTTON_LIST_OPEN            553
#define IDC_BUTTON_LIST_SORT            556
#define IDC_BUTTON_GO2                  558
#define IDC_BUTTON_EXIT                 560
#define IDC_RADIO_ZSORT                 561
#define IDC_RADIO_TARGET1               563
#define IDC_RADIO_TARGET2               565
#define IDC_RADIO_FORM_OPTION1          567
#define IDC_BUTTON_FORMOPTION_FORM_NAME 569
#define IDC_CHECK_INCREASE              571
#define IDC_RADIO_NSORT                 632
#define IDC_RADIO_NMSORT                634
#define IDC_RADIO_ZMSORT                636
#define IDC_STATIC_INSERT_LOCATION      720
#define IDC_STATIC_TEXT_OPTION_FONT     721
#define IDC_STATIC_TEXT_OPTION_LAYER    722
#define IDC_STATIC_TEXT_OPTION_HEIGHT   723
#define IDC_STATIC_TEXT_OPTION_WIDTH    724
#define IDC_STATIC_TEXT_OPTION_ANGLE    725
#define IDC_STATIC_INCREASE_START_NUMBER 726
#define IDC_STATIC_INCREASE_DIGIT       727
#define IDC_STATIC_PREVIEW_LABEL        728
#define IDC_STATIC_WRITE_DWG_NAME_FONT  729
#define IDC_STATIC_WRITE_DWG_NAME_LAYER 730
#define IDC_STATIC_WRITE_DWG_NAME_TEXT_HEIGHT 731
#define IDC_STATIC_WRITE_DWG_NAME_TEXT_WIDTH 732
#define IDC_STATIC_WRITE_DWG_NAME_ALIGN 733
#define IDC_STATIC_WRITE_DWG_NAME_TEXT_ANGLE 734
#define IDC_STATIC_PREVIEW_LABEL2       735
//#define IDS_HORIZON_DRAW                736
//#define IDS_LEADER_DRAW                 737
#define IDC_CALS_RADMODEL               2000
#define IDC_CALS_RADLAYOUT              2001
#define IDC_CALS_RADMODELLAY            2002
#define IDC_CALS_RADCERTAIN             2003
#define IDC_CALS_RADACTIVE              2005
#define IDS_EXPORT_COORDS_CHK           2006
#define IDS_PATH_CHECK                  2007
#define IDS_NOTOPEN_EXCEL               2008
#define IDS_DONOTOPEN_EXCEL             2009
#define IDS_NOTSET_PATH                 2010
#define IDS_IMPORT_EXCEL_COORDS         2011
#define IDS_EXCEL_TO_CAD                2012
#define IDS_SET_EXCEL_AREA              2013
#define IDS_EXCEL_LINE_CHECK            2014
#define IDS_BLOCK_IN_CAD                2015
#define IDS_COA_FIRST_SEL               2016
#define IDS_COA_SECOND_SEL              2017
#define IDS_INPUT_COA_VALUE             2018
#define IDS_GET_LAYER_ENTITY            2019
#define IDS_SLOPE_SELECT                2020
#define IDS_GROUND_SELECT               2021
#define IDS_GROUND_SLOPE_CHK            2022
#define IDS_SEL_ROUNDING                2023
#define IDS_SEL_SECOND                  2024
#define IDS_COLOR_CHECK                 2025
#define IDS_FIRST_STA_SELECT            2026
#define IDS_SECOND_STA_SELECT           2027
#define IDS_MODIFY_TEXT_SEL             2028
#define IDS_CAL_TXT_INTPT_SEL           2029
#define IDS_EXIST_FILE                  2030
#define IDS_CUT_FIRST_SEL               2031
#define IDS_CUT_SECOND_SEL              2032
#define IDS_CHECK_PLINE                 2033
#define IDS_SLOPE_CHECK                 2034
#define IDS_CHECK_SCALE                 2035
#define IDS_NOT_CHECK_COLOR             2036
#define IDS_CROSS_CORNER_SEL            2037
#define IDS_CROSS_OPPOSITE_SEL          2038
#define IDS_CROSS_CENTER_SEL            2039
#define IDS_CLOSED_PLINE_SEL            2040
#define IDS_EL_INPUT                    2041
#define IDS_CHECK_LAYER_COLOR           2042
#define IDS_EL_CHECK_MSG                2043
#define IDS_STYLE_HEIGHT_TEXT           2044
#define IDS_SELECT_CANCEL               2045
#define IDS_FIRST_SELECT                2046
#define IDS_SECOND_SELECT               2047
#define IDS_THIRD_SELECT                2048
#define IDS_SLOPE_START                 2049
#define IDS_SLOPE_END                   2050
#define IDS_BERM_MSG                    2051
#define IDS_BERM_CHECK                  2052
#define IDS_BERM_RESTART                2053
#define IDS_SEL_LAY_CANCEL              2054
#define IDS_VERT_START_SEL              2055
#define IDS_VERT_END_SEL                2056
#define IDS_GRID_TOP_SEL                2057
#define IDS_LTYPE_CHANGE_SEL            2058
#define IDS_DLT_TYPE                    2059
#define IDS_INPUT_SCALE                 2060
#define IDS_CHOICE_REVERSE              2061
#define IDS_SELECT_CONFIRME             2062
#define IDS_DRL_FIRST_SELECT            2063
#define IDS_DRL_INPUT_SCALE             2064
#define IDS_LEAN_THK                    2065
#define IDS_DRL_SECOND_SELECT           2066
#define IDS_LINE_TOP                    2067
#define IDS_LINE_BOTTOM                 2068
#define IDS_LINE_VERTICAL               2069
#define IDS_LINE_BOTTOM_VERT            2070
#define IDS_ZERO_HIDE                   2071
#define IDS_KM_HIDE                     2072
#define IDS_SEL_CHK_PLINE_LINE          2073
#define IDS_FEL_BASEPT_SEL              2074
#define IDS_SET_CMD_SCALE               2075
#define IDS_SET_SCALE                   2076
#define IDS_FEL_INPUT_SCALE             2077
#define IDS_CHECK_STRING_ENTER          2078
#define IDS_FEL_BASE_SEL                2079
#define IDS_FEL_EL_INPUT                2080
#define IDS_LEN_HOR_LINE                2081
#define IDS_LEN_LEAD_LINE               2082
#define IDS_RUN_CHECK_EXCEL             2083
#define IDS_LOAD_LINE_SEL               2084
#define IDS_SELECT_CHK_LINE             2085
#define IDS_LINE_DIRECT_CHK             2086
#define IDS_BASE_LOAD_POINT             2087
#define IDS_POINT_INPUT                 2088
#define IDS_OPPO_LOAD_LINE_SEL          2089
#define IDS_GEL_START_SEL               2090
#define IDS_GEL_START_EL_SEL            2091
#define IDS_GEL_END_SEL                 2092
#define IDS_GEL_END_EL_SEL              2093
#define IDS_CAL_BASELINE_SEL            2095
#define IDS_CHECK_PLINE_CMD             2096
#define IDS_BYBLOCK                     2097
#define IDS_BYLAYER                     2098
#define IDS_GEL_EL_PICK                 2099
#define IDS_LINE_SELECT                 2100
#define IDS_CIVIL_BASEPT                2101
#define IDS_CIVIL_CHECK_PT              2102
#define IDS_CIVIL_POINT                 2103
#define IDS_EXCEL_AREA_SEL              2104
#define IDS_EXPORT_EXCEL_COORDS         2105
#define IDS_CIVIL_LEADER_INPUT          2106
#define IDS_CIVIL_LEADER_DIRECT         2107
#define IDS_LEFT                        2108
#define IDS_RIGHT                       2109
#define IDS_EVERYTHING                  2110
#define IDS_SEL_CHECK_ENTITY            2111
#define IDS_SET_TEXT                    2112
#define IDS_ZVL_START_SET               2113
#define IDS_ZVL_SEL_Z_INPUT             2114
#define IDS_NEXT_PT_SET                 2115
#define IDS_INSERT_PT_SET               2116
#define IDS_CMD_SEL_Z_INPUT             2117
#define IDS_GET_TEXT_ENTITY             2118
#define IDS_CIVIL_ANG_INPUT             2119
#define IDS_CIVIL_DIST_INPUT            2120
#define IDS_FIRST_SEL_CMD               2121
#define IDS_SECOND_SEL_CMD              2122
#define IDS_ID_PT_SEL                   2123
#define IDS_END_PT_SEL                  2124
#define IDS_CROSS_CEN_SEL               2125
#define IDS_HORIZON_DRAW				2126
#define IDS_LEADER_DRAW					2127
#define IDS_SLOPE_SEARCH_SEL            2128
#define IDS_PERCENT_RESULT              2129
#define IDS_PERCENT_DISPLAY             2130
#define IDS_SET_VHSCALE                 2131
#define IDS_START_SEL                   2132
#define IDS_SET_HSCALE                  2133
#define IDS_SET_VSCALE                  2134
#define IDS_DIRECT_SEL                  2135
#define IDS_SLOPE_INPUT                 2136
#define IDS_RECT_INPUT                  2137
#define IDD_DIALOG_ATTRIBUTE            10000
#define IDD_EMTT                        10001
#define IDC_LIST_ATT                    10016
#define IDC_STATIC_MSG                  10017
#define IDC_STATIC_SELECT_TAG           10018
#define ID_H_SLT1                       32768
#define ID_H_SLT2                       32769
#define ID_H_SLT3                       32770
#define ID_H_SLT4                       32771
#define ID_H_SLT5                       32772
#define ID_H_SLT6                       32773
#define ID_H_SLT7                       32774
#define IDC_SLT_GROUP0                  65535
#define IDS_USER_DLT_TYPE				32775


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         313
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
