//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CT_CIVIL.rc
//
#define IDOK                            1
#define IDCANCEL                        2
#define IDS_PROJNAME                    100
#define IDS_STRING101                   101
#define IDD_DIALOG1                     102
#define IDS_STRING102                   102
#define IDD_NSLO                        103
#define IDS_STRING103                   103
#define IDB_BITMAP1                     104
#define IDS_STRING104                   104
#define IDB_BITMAP2                     105
#define IDS_STRING105                   105
#define IDB_BITMAP3                     106
#define IDS_STRING106                   106
#define IDD_GEL                         107
#define IDS_STRING107                   107
#define IDD_DSLO                        108
#define IDS_STRING108                   108
#define IDS_STRING109                   109
#define IDB_BITMAP4                     110
#define IDS_STRING110                   110
#define IDB_BITMAP5                     111
#define IDS_STRING111                   111
#define IDD_CEX                         112
#define IDS_STRING112                   112
#define IDS_STRING113                   113
#define IDB_BITMAP6                     114
#define IDS_STRING114                   114
#define IDB_BITMAP7                     115
#define IDS_STRING115                   115
#define IDB_BITMAP8                     116
#define IDS_STRING116                   116
#define IDB_BITMAP9                     117
#define IDS_STRING117                   117
#define IDC_COMBO1                      118
#define IDC_CBXLAYER                    118
#define IDD_CIM                         118
#define IDC_LAYER                       118
#define IDC_CSTYLE                      118
#define IDS_STRING118                   118
#define IDC_CBXSTALAYER                 118
#define IDC_CBX_LAYER                   118
#define IDC_RADIO1                      119
#define IDD_DCW                         119
#define IDC_CLAYER                      119
#define IDS_STRING119                   119
#define IDC_STT_CBXDOT                  119
#define IDC_RADIO2                      120
#define IDD_WCZ                         120
#define IDS_STRING120                   120
#define IDC_STT_CBXLINE                 120
#define IDC_RADIO3                      121
#define IDC_LINE                        121
#define IDS_STRING121                   121
#define IDD_DSTA                        121
#define IDC_STT_CBXTEXT                 121
#define IDC_BLOCK                       122
#define IDS_STRING122                   122
#define IDI_ICON1                       122
#define IDI_ZDREAM_2017                 122
#define IDC_STT_CBXLAYERDOT             122
#define IDC_POLYLINE                    123
#define IDS_STRING123                   123
#define IDD_COA                         123
#define IDC_CIRCLE                      124
#define IDS_STRING124                   124
#define IDD_XYB                         124
#define IDC_CHKDRAWLINE                 125
#define IDC_TEXT                        125
#define IDS_STRING125                   125
#define IDC_EDTMAXDIST                  126
#define IDC_DONUT                       126
#define IDC_POINTBTN                    126
#define IDS_STRING126                   126
#define IDC_CHKCHANGELAYER              127
#define IDC_TEXTFILE                    127
#define IDC_CIRCLEBTN                   127
#define IDS_STRING127                   127
#define IDB_BITMAP10                    127
#define IDC_BCOLOR                      128
#define IDC_POINT                       128
#define IDC_BLOCKBTN                    128
#define IDS_STRING128                   128
#define IDD_ZVT                         128
#define IDC_EDTAUTODIST                 129
#define IDC_ARC                         129
#define IDS_STRING129                   129
#define IDD_ZVL                         129
#define IDC_CHKAUTODRAW                 130
#define IDC_ZAXIS                       130
#define IDS_STRING130                   130
#define IDD_TTP                         130
#define IDC_STTBIT1                     131
#define IDC_EXCEPT                      131
#define IDS_STRING131                   131
#define IDD_FEL                         131
#define IDC_STTBIT2                     132
#define IDC_CONTEXT                     132
#define IDS_STRING132                   132
#define IDD_DCON                        132
#define IDC_STTBIT3                     133
#define IDC_CHKARRAY                    133
#define IDS_STRING133                   133
#define IDB_FORM1                       133
#define IDC_STTWIDTH                    134
#define IDC_POINTEDIT                   134
#define IDS_STRING134                   134
#define IDB_FORM2                       134
#define IDC_BSELECT                     135
#define IDS_STRING135                   135
#define IDB_FORM3                       135
#define IDC_PATH                        136
#define IDS_STRING136                   136
#define IDB_FORM4                       136
#define IDC_STT_BSELECT2                136
#define IDC_CHKADDPOINT                 137
#define IDC_PATHINPUT                   137
#define IDS_STRING137                   137
#define IDB_FORM5                       137
#define IDC_STT_BSELECT3                137
#define IDC_ALL_DEL                     137
#define IDC_CHKEXTEND                   138
#define IDC_Colon                       138
#define IDS_STRING138                   138
#define IDD_CST                         138
#define IDC_STT_BSELECT4                138
#define IDC_EDTEXTENDSTR                139
#define IDC_SPACE                       139
#define IDS_STRING139                   139
#define IDD_FE                          139
#define IDC_BTN_ACTIVEDWG_ADD           139
#define IDC_EDTSCALE                    140
#define IDC_SET                         140
#define IDS_STRING140                   140
#define IDD_GST                         140
#define IDC_EDTELSTR                    141
#define IDC_RIGHT                       141
#define IDS_STRING141                   141
#define IDD_STT                         141
#define IDC_BTN_BOTTOM                  141
#define IDC_EDTDOTNUM                   142
#define IDC_EXCEL                       142
#define IDS_STRING142                   142
#define IDC_FEDECIMAL                   142
#define IDD_FW                          142
#define IDC_SPINDOT                     143
#define IDC_LEFT                        143
#define IDC_2DPOLY                      143
#define IDS_STRING143                   143
#define IDC_FESCALE                     143
#define IDD_AZT                         143
#define IDC_EDTTEXTHEIGHT               144
#define IDC_DOWN                        144
#define IDS_STRING144                   144
#define IDD_GCS                         144
#define IDC_UP                          145
#define IDS_STRING145                   145
#define IDC_FEPREFACE                   145
#define IDD_SLT                         145
#define IDC_BTN_DOWN                    145
#define IDC_BLAYERSELECT                146
#define IDC_EXCELFILE                   146
#define IDS_STRING146                   146
#define IDC_FEHEIGHT                    146
#define IDB_SLT1                        146
#define IDC_BTN_FILELISTSAVE            146
#define IDC_BTEXTSELECT                 147
#define IDC_PIC1                        147
#define IDS_STRING147                   147
#define IDB_SLT2                        147
#define IDC_CHKDRAWARROW                148
#define IDC_PIC2                        148
#define IDR_MENU1                       148
#define IDC_BTN_OPENDWG_ADD             148
#define IDC_BUTTON1                     149
#define IDC_PIC3                        149
#define IDD_DLG                         149
#define IDC_EDIT1                       150
#define IDC_PIC4                        150
#define IDC_EDIT_3                      150
#define IDC_EDTSTADIST                  150
#define IDC_EDTXOFFSET                  150
#define IDC_EDTLENGTH                   150
#define IDC_EDT_BASE                    150
#define IDC_STT_EDTSCALE                150
#define IDC_EDT_VSCALE                  150
#define IDD_CSR                         150
#define IDC_EDT_SCALE                   150
#define IDC_EDIT2                       151
#define IDC_SETSPACE                    151
#define IDC_EDIT_2                      151
#define IDC_EDTSTALINE                  151
#define IDC_EDTY                        151
#define IDC_EDTTEXTWIDHT                151
#define IDC_EDTYOFFSET                  151
#define IDC_EDTHEIGHT                   151
#define IDC_EDT_LAYERNAME               151
#define IDC_STT_EDTSTLENGTH             151
#define IDC_EDT_GRIDDIST                151
#define IDC_EDT_TRIMDIST                151
#define IDD_ADN                         151
#define IDC_MINUS                       152
#define IDC_STT_EDTDIST                 152
#define IDC_SLT_ARROWHEIGHT             152
#define IDD_DFB                         152
#define IDC_SPIN1                       153
#define IDC_PLUS                        153
#define IDC_SPIN_2                      153
#define IDC_SPNDECIMALPOINT             153
#define IDC_EDTDIST                     153
#define IDC_SPN_BRIGHT                  153
#define IDC_STT_EDTHEIGHT               153
#define IDC_STT_EDTWIDTH                154
#define IDC_SPIN2                       155
#define IDC_SPIN_1                      155
#define IDC_SLT_LEADER                  155
#define IDC_BTN_TOP                     155
#define IDC_CHECK1                      156
#define IDC_POINTCOLORBTN               156
#define IDC_SLT_EDTDOT                  156
#define IDC_BTN_UP                      156
#define IDC_EDTSTARTVALUE               157
#define IDC_XYCHANGE                    157
#define IDC_CHECKFEHPOINT               157
#define IDC_SLT_EDTHORSCALE             157
#define IDC_SPIN_3                      157
#define IDC_EDTENDVALUE                 158
#define IDC_PATHBTN                     158
#define IDC_SLT_EDTVERSCALE             158
#define IDC_BSELECTELVALUE              159
#define IDC_TEXTBTN                     159
#define IDC_SLT_EDTDISTDOT              159
#define IDC_CONLINECOLORBTN             160
#define IDC_EDIT_1                      160
#define IDC_SLT_EDTHEIGHTDOT            160
#define IDC_ZVALCOLORBTN                161
#define IDC_STATIC_1                    161
#define IDC_TEXTLOAD                    162
#define IDC_STATIC_2                    162
#define IDC_TEXTLAYER                   163
#define IDC_STATIC_3                    163
#define IDC_TEXTSIZE                    164
#define IDC_SPIN3                       164
#define IDC_STATIC_4                    164
#define IDC_SLT_SPIN1                   164
#define IDC_XOFF                        165
#define IDC_EDTSTASTART                 165
#define IDC_SLT_SPIN2                   165
#define IDC_YOFF                        166
#define IDC_CHKSTACIRCLE                166
#define IDC_SLT_SPIN3                   166
#define IDC_SELTEXT                     167
#define IDC_EDTSTACIRCLE                167
#define IDC_BTNSTASELECT                168
#define IDC_CBXTEXTPOSITION             169
#define IDC_CHKTEXTVISIBLE              170
#define IDC_EDTTEXTDIST                 171
#define IDC_EDTTEXTOFFSET               172
#define IDC_EDTDECIMALPOINT             173
#define IDC_BNAME                       174
#define IDC_ZCHECK                      175
#define IDC_EDTTEXTSIZE                 175
#define IDC_3DPOLY                      176
#define IDC_BTNTEXTSELECT               176
#define IDC_SELLAYER                    177
#define IDC_TEXTSEL                     177
#define IDC_CBXTEXTSTYLE                177
#define IDC_CBXTEXTLAYER                178
#define IDC_POINTPICCOLOR               179
#define IDC_BTNTEXTCOLOR                179
#define IDC_CONLINE                     180
#define IDC_CHKONEWAY                   180
#define IDC_RADSTA                      180
#define IDC_CONLINELAYER                181
#define IDC_FACTOR                      181
#define IDC_RADNO                       181
#define IDC_TCPICCOLOR                  182
#define IDC_THICKNESS                   182
#define IDC_CHKSTASTART                 182
#define IDC_CONLINEPICCOLOR             183
#define IDC_COLORFACTOR                 183
#define IDC_BTNSTACOLOR                 183
#define IDC_ZVALPICCOLOR                184
#define IDC_FACTORSPACE                 184
#define IDC_STTSTACOLORINDEX            184
#define IDC_SELCONLINE                  185
#define IDC_DIVISION                    185
#define IDC_STTTEXTCOLORINDEX           185
#define IDC_CUTPOINT                    186
#define IDC_CHKARROW                    186
#define IDC_BUTTON2                     186
#define IDC_BTEXT                       186
#define IDC_SLT_BTN4                    186
#define IDC_STATICDCS                   187
#define IDC_CUTPOINTLAYER               187
#define IDC_RANGLE                      187
#define IDC_CHECK2                      187
#define IDC_CHKEXPLODE                  187
#define IDC_CHKZV                       187
#define IDC_CHECKFEHORIZONTAL           187
#define IDC_STT_CHECK2                  187
#define IDC_SLT_BTN5                    187
#define IDC_CHK_CONTINUOUS              187
#define IDC_CHK_ROUNDINGTRIM            187
#define IDC_POINTSIZE                   188
#define IDC_RECTANGLE                   188
#define IDC_BPOINT                      188
#define IDC_STT_CHECK3                  188
#define IDC_DIAMETER                    189
#define IDC_TEXTHEIGHT                  189
#define IDC_EDTX                        189
#define IDC_STT_CHECK4                  189
#define IDC_SCALE                       190
#define IDC_TEXTWIDTH                   190
#define IDC_SELZVALUE                   191
#define IDC_CELVATION                   191
#define IDC_ZVALUE                      192
#define IDC_COABIT                      192
#define IDC_ZVALUELAYER                 193
#define IDC_SELPOINT                    194
#define IDC_CBXPOINTLAYER               194
#define IDC_TEXTSIZE4                   195
#define IDC_RADRIGHT                    195
#define IDC_FILELISTSAVE                195
#define IDC_XOFF4                       196
#define IDC_CHKCP                       196
#define IDC_YOFF4                       197
#define IDC_RADUP                       197
#define IDC_PCNT                        198
#define IDC_RADDOWN                     198
#define IDC_RADLEFT                     199
#define IDC_RADLINE                     201
#define IDC_RADPLINE                    202
#define IDC_LIST_FILES                  203
#define IDC_RADINSERTPOINT              204
#define IDC_RADALIGNPOINT               205
#define IDC_COMBO_EXTENSION             205
#define IDC_EDTHEADER                   206
#define IDC_EDIT4                       207
#define IDC_EDTPOINT                    207
#define IDC_STT_EDTDOT                  207
#define IDC_STT_EDTDIST2                208
#define IDC_RADARROW                    209
#define IDC_STT_EDTOFFSET               209
#define IDC_STATICRADTEXT               210
#define IDC_EDT_BRIGHT                  211
#define IDC_CHK_LAYERCOLOR              213
#define IDC_BTN_COLOR                   214
#define IDC_STATICFWLAYER               214
#define IDC_STATICFWTXTLAYER            215
#define IDC_RAD_CIVIL                   215
#define IDC_FWLINELAYER                 216
#define IDC_RAD_CAD                     216
#define IDC_FWTXTLAYER                  217
#define IDC_EDT_LINESCALE               217
#define IDC_STATICFWTXTHEIGHT           218
#define IDC_CHK_STANDARD                218
#define IDC_STATICFWTXTWIDTH            219
#define IDC_STT_COLOR                   219
#define IDC_STATICFWLDLENGTH            220
#define IDC_CHK_EXPLODE                 220
#define IDC_STATICFWLDLENGTH2           221
#define IDC_RAD_SELECTDIST              221
#define IDC_FWFORM1                     222
#define IDC_RAD_HORIZON                 222
#define IDC_FWTXTHEIGHT                 223
#define IDC_RAD_INTERSECTION            223
#define IDC_FWTXTWIDTH                  224
#define IDC_CHK_BASETRIM                224
#define IDC_FWLDLENGTH                  225
#define IDC_CHKTEXT                     225
#define IDC_FWDECIMAL                   226
#define IDC_STATICFWPREFACE             227
#define IDC_FWPREFACE                   228
#define IDC_STATICFWNOTATION            229
#define IDC_FWFORM2                     230
#define IDC_FWFORM3                     231
#define IDC_FWFORM4                     232
#define IDC_FWFORM5                     233
#define IDC_FORMGROUP                   235
#define IDC_PICFORM                     237
#define IDC_SEL_DEL                     237
#define IDC_CHECKFELEADER               238
#define IDC_SORT1                       238
#define IDC_STATICFEDOT                 239
#define IDC_SORT2                       239
#define IDC_STATICFELAYER               240
#define IDC_STATICFEPREFACE             241
#define IDC_STATICFEHEIGHT              242
#define IDC_FELAYER                     243
#define IDC_STATICFESCALE               244
#define IDC_CHECKFESPOINT               245
#define IDC_STATICFEEL                  246
#define IDC_RADIOFEUP                   247
#define IDC_RADIOFEDOWN                 248
#define IDC_STT_STATIC1                 250
#define IDC_STT_STATIC_SCALE            251
#define IDC_STT_STATIC_LENGTH           252
#define IDC_STT_STATIC_PTWIDTH          253
#define IDC_STT_STATIC_TXTHEIGHT        254
#define IDC_STATIC_TXTWIDTH             255
#define IDC_STT_STATIC_TXTTYPE          256
#define IDC_STT_STATIC_DOT              257
#define IDC_STT_STATIC2                 258
#define IDC_SLT_STATIC_COLOR            258
#define IDC_STT_STATIC_OFFSET           259
#define IDC_STT_STATIC_LAYERLINE        260
#define IDC_STT_STATIC_LAYERTXT         261
#define IDC_STT_STATIC_LAYERDOT         262
#define IDC_STT_RADSTATION              263
#define IDC_STT_RADNUMBER               264
#define IDC_STT_CHECK1                  265
#define IDC_STT_CBXTEXTTYPE             266
#define IDC_STT_STATIC_M1               267
#define IDC_SLT_STATIC12                267
#define IDC_STT_STATIC_M2               268
#define IDC_SLT_STATIC13                268
#define IDC_STT_STATIC_M3               269
#define IDC_SLT_STATIC14                269
#define IDC_STT_BSELECT1                270
#define IDC_GST_STATIC_MARK             271
#define IDC_SLT_CHECK2                  271
#define IDC_GST_RADSTATION              272
#define IDC_SLT_CHECK3                  272
#define IDC_GST_RADNUMBER               273
#define IDC_SLT_STATIC4                 273
#define IDC_CST_RADEDIT                 274
#define IDC_GST_STATIC_STLENGTH         274
#define IDC_SLT_STATIC2                 274
#define IDC_GST_STATIC_DOT              275
#define IDC_SLT_STATIC5                 275
#define IDC_STATICCOME                  276
#define IDC_CST_RADWRITE                276
#define IDC_GST_STATIC_SCALE            276
#define IDC_SLT_STATIC3                 276
#define IDC_POINTCOLOR                  277
#define IDC_GST_STATIC_DIST             277
#define IDC_SLT_STATIC6                 277
#define IDC_TCOLOR                      278
#define IDC_GST_CHECK2                  278
#define IDC_SLT_STATIC9                 278
#define IDC_CONCOLOR                    279
#define IDC_GST_CHECK1                  279
#define IDC_SLT_BSELECT2                279
#define IDC_ZVALCOLOR                   280
#define IDC_GST_STATIC_TXTHEIGHT        280
#define IDC_SLT_BSELECT3                280
#define IDC_GST_STATIC_PREFACE          281
#define IDC_AZT_BSELECT3                281
#define IDC_SLT_CHECK4                  281
#define IDC_CST_STATIC_FOOTER           282
#define IDC_GST_EDTSTLENGTH             282
#define IDC_SLT_STATIC_RATIO            282
#define IDC_GST_CBXDOT                  283
#define IDC_AZT_CHECK1                  283
#define IDC_GST_EDTSCALE                284
#define IDC_AZT_CHECK2                  284
#define IDC_GST_EDTDIST                 285
#define IDC_AZT_CHECK3                  285
#define IDC_GST_EDTHEIGHT               286
#define IDC_GST_BSELECT                 287
#define IDC_GST_EDTPREFACE              288
#define IDC_GST_GROUP                   289
#define IDC_CST_GROUP                   290
#define IDC_GST_CHECK3                  290
#define IDC_CST_EDTFOOTER               291
#define IDC_CST_STATIC_MARK             292
#define IDC_CST_RADSTATION              293
#define IDC_CST_RADNUMBER               294
#define IDC_CST_STATIC_DOT              295
#define IDC_CST_CBXDOT                  296
#define IDC_CST_STATIC_DIST             297
#define IDC_CST_EDTDIST                 298
#define IDC_CST_STATIC_TXTHEIGHT        299
#define IDC_CST_EDTHEIGHT               300
#define IDC_CST_BSELECT                 301
#define IDC_CST_STATIC_PREFACE          302
#define IDC_CST_EDTPREFACE              303
#define IDC_CST_STATIC                  304
#define IDC_GCS_STATIC_MARK             309
#define IDC_SLT_GROUP4                  309
#define IDC_GCS_RADSTATION              310
#define IDC_SLT_GROUP5                  310
#define IDC_GCS_RADNUMBER               311
#define IDC_GCS_STATIC_DOT              313
#define IDC_GCS_CBXDOT                  314
#define IDC_GCS_STATIC_DIST             315
#define IDC_GCS_EDTDIST                 316
#define IDC_GCS_CHECK1                  317
#define IDC_GCS_STATIC_REFROAD          318
#define IDC_GCS_STATIC_CORROAD          319
#define IDC_GCS_EDTREFROAD              320
#define IDC_GCS_EDTCORROAD              321
#define IDC_GCS_CHECK2                  322
#define IDC_SLT_BTN1                    323
#define IDC_SLT_BTN2                    324
#define IDC_SLT_GROUP2                  326
#define IDC_SLT_RADPERCENT              327
#define IDC_AZT_FORM2                   328
#define IDC_SLT_RADRATIO                328
#define IDC_AZT_FORM3                   329
#define IDC_SLT_CHECK1                  329
#define IDC_SLT_BTN3                    330
#define IDC_SLT_STATIC1                 331
#define IDC_SLT_ARROWWIDTH              332
#define IDC_SLT_STATIC7                 333
#define IDC_SLT_STATIC8                 334
#define IDC_SLT_STATIC10                335
#define IDC_AZT_STATIC2                 336
#define IDC_SLT_BSELECT1                336
#define IDC_SLT_STATIC11                337
#define IDC_SLT_STATIC15                338
#define IDC_AZT_STATIC6                 339
#define IDC_SLT_CBXTEXTTYPE             339
#define IDC_SLT_CBXLAYER                340
#define IDC_AZT_CBXTEXTSTYLE            341
#define IDC_SLT_EDTHEIGHT               341
#define IDC_SLT_STATIC_PERCENT          342
#define IDC_AZT_CBXLAYER2               343
#define IDC_SLT_PRINCOLOR               343
#define IDC_SLT_WRITE                   357
#define IDC_AZT_GROUP1                  358
#define IDC_AZT_GROUP2                  359
#define IDC_AZT_GROUP4                  360
#define IDC_AZT_FORM1                   361
#define IDC_AZT_STATIC1                 362
#define IDC_AZT_STATIC3                 363
#define IDC_AZT_STATIC4                 364
#define IDC_AZT_STATIC5                 365
#define IDC_AZT_CBXLAYER1               366
#define IDC_AZT_BSELECT1                367
#define IDC_AZT_BSELECT2                368
#define IDC_AZT_EDTHEIGHT               369
#define IDC_AZT_EDTWIDTH                370
#define IDC_AZT_DOT                     371
#define IDC_AZT_SPIN                    372
#define IDC_AZT_OK                      373
#define ID_H_SLT1                       32768
#define ID_H_SLT2                       32769
#define ID_H_SLT3                       32770
#define ID_H_SLT4                       32771
#define ID_H_SLT5                       32772
#define ID_H_SLT6                       32773
#define ID_H_SLT7                       32774
#define IDC_SLT_GROUP0                  65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         226
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
